-- Initial PostgreSQL schema (TASK-15). Matches the JPA entities; the prod profile runs Hibernate with
-- ddl-auto=validate, so any entity change needs a new V<n>__*.sql migration here.
-- Enum columns keep CHECK constraints: adding an enum value (e.g. a Role) also needs a migration.

create table users (
    id               bigint generated by default as identity primary key,
    login_identifier varchar(100)             not null,
    password_hash    varchar(255)             not null,
    status           varchar(20)              not null check (status in ('PENDING', 'ACTIVE', 'INACTIVE')),
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone not null,
    constraint uk_users_login_identifier unique (login_identifier)
);

create table user_roles (
    user_id bigint      not null,
    role    varchar(30) not null check (role in ('USER', 'ADMIN', 'CONFIRMER')),
    primary key (user_id, role),
    constraint fk_user_roles_user foreign key (user_id) references users (id)
);

create table posts (
    id         bigint generated by default as identity primary key,
    author_id  bigint                      not null,
    title      varchar(200)                not null,
    content    varchar(10000)              not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint fk_posts_author foreign key (author_id) references users (id)
);

create index idx_posts_author_id on posts (author_id);

-- start_at / end_at are wall-clock times in the service time zone (Asia/Seoul, DECISIONS D-030).
create table schedules (
    id          bigint generated by default as identity primary key,
    title       varchar(200)                not null,
    description varchar(5000),
    start_at    timestamp(6)                not null,
    end_at      timestamp(6)                not null,
    status      varchar(30)                 not null check (status in ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    priority    varchar(30)                 not null check (priority in ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    assignee_id bigint,
    location    varchar(300),
    is_public   boolean                     not null,
    color       varchar(20),
    created_by  bigint                      not null,
    created_at  timestamp(6) with time zone not null,
    updated_by  bigint                      not null,
    updated_at  timestamp(6) with time zone not null,
    deleted     boolean                     not null,
    version     bigint                      not null,
    constraint fk_schedules_assignee foreign key (assignee_id) references users (id),
    constraint fk_schedules_created_by foreign key (created_by) references users (id),
    constraint fk_schedules_updated_by foreign key (updated_by) references users (id)
);

create index idx_schedules_deleted_start_at on schedules (deleted, start_at);
create index idx_schedules_end_at on schedules (end_at);
create index idx_schedules_status on schedules (status);
create index idx_schedules_assignee_id on schedules (assignee_id);
create index idx_schedules_created_by on schedules (created_by);

create table schedule_rewards (
    id           bigint generated by default as identity primary key,
    schedule_id  bigint                      not null,
    recipient_id bigint                      not null,
    points       integer                     not null,
    reason       varchar(500)                not null,
    status       varchar(20)                 not null check (status in ('PENDING', 'PAID', 'CANCELLED')),
    created_by   bigint                      not null,
    created_at   timestamp(6) with time zone not null,
    updated_by   bigint                      not null,
    updated_at   timestamp(6) with time zone not null,
    paid_at      timestamp(6) with time zone,
    version      bigint                      not null,
    constraint fk_schedule_rewards_schedule foreign key (schedule_id) references schedules (id),
    constraint fk_schedule_rewards_recipient foreign key (recipient_id) references users (id),
    constraint fk_schedule_rewards_created_by foreign key (created_by) references users (id),
    constraint fk_schedule_rewards_updated_by foreign key (updated_by) references users (id)
);

create index idx_schedule_rewards_schedule_id on schedule_rewards (schedule_id);
create index idx_schedule_rewards_recipient_status on schedule_rewards (recipient_id, status);
create index idx_schedule_rewards_status on schedule_rewards (status);
