-- Study timer (TASK-TIMER-01): per-user subjects, study sessions and a daily goal.
-- New tables need RLS in the same migration (DECISIONS D-044).

create table study_subjects (
    id         bigint generated by default as identity primary key,
    user_id    bigint                      not null,
    name       varchar(20)                 not null,
    sort_order integer                     not null,
    created_at timestamp(6) with time zone not null,
    constraint uk_study_subjects_user_name unique (user_id, name),
    constraint fk_study_subjects_user foreign key (user_id) references users (id)
);

-- record_date: the Asia/Seoul day the time counts for. Timer sessions keep their real start/end instants;
-- MANUAL ones may have neither.
create table study_sessions (
    id           bigint generated by default as identity primary key,
    user_id      bigint                      not null,
    subject_id   bigint                      not null,
    mode         varchar(20)                 not null check (mode in ('STOPWATCH', 'POMODORO_FOCUS', 'MANUAL')),
    record_date  date                        not null,
    start_time   timestamp(6) with time zone,
    end_time     timestamp(6) with time zone,
    paused_at    timestamp(6) with time zone,
    paused_sec   bigint                      not null,
    planned_sec  integer,
    duration_sec integer                     not null,
    completed    boolean                     not null,
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    version      bigint                      not null,
    constraint fk_study_sessions_user foreign key (user_id) references users (id),
    constraint fk_study_sessions_subject foreign key (subject_id) references study_subjects (id)
);

create index idx_study_sessions_user_date on study_sessions (user_id, record_date);
create index idx_study_sessions_user_completed on study_sessions (user_id, completed);
create index idx_study_sessions_subject_id on study_sessions (subject_id);

create table study_goals (
    user_id        bigint                      not null primary key,
    daily_goal_sec integer                     not null,
    updated_at     timestamp(6) with time zone not null,
    constraint fk_study_goals_user foreign key (user_id) references users (id)
);

alter table study_subjects enable row level security;
alter table study_sessions enable row level security;
alter table study_goals enable row level security;
